development:
  clients:
    default:
      database: web_crawler_development
      hosts:
        - localhost
production:
  clients:
    default:
      database: sample_webcrawler
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        raise_not_found_error: false
test:
  clients:
    default:
      database: web_crawler_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
